package controllers

import app.Loader
import org.scalatestplus.play._
import org.scalatestplus.play.guice.GuiceOneServerPerSuite
import play.api.{Application, ApplicationLoader, Environment}

class ShowcaseControllerSpec extends PlaySpec
  with GuiceOneServerPerSuite
  with OneBrowserPerSuite
  with HtmlUnitFactory {

  implicit override lazy val app: Application =
    (new Loader).load(ApplicationLoader.createContext(Environment.simple()))

//  private lazy val root = s"http://localhost:$port/scommons-showcase"
//
//  "Application" must {
//    "load the page without error" in {
//      go to (root + "/index.html")
//      pageTitle mustBe ""
//      //find(id("root")).value.text mustBe "Hello, world!"
//      println("text: " + find(xpath("htmp:body:div")).value.text)
//    }
//
//    "load assets generated by webpack" in {
//      go to (root + "/assets/styles/styles.css")
//      pageSource must include("url(../styles/")
//    }
//  }
}
